stages:
  - build

build:
  stage: build
  tags:
    - development
  only:
    - /^\d+\.\d+\.\d+$/
  script:
    - docker build . -t docker.dev.slicelife.com/metadataproxy:${CI_COMMIT_TAG}
    - docker push docker.dev.slicelife.com/metadataproxy:${CI_COMMIT_TAG}
